### PR TITLE
feat: created login/landing page

### PR DESCRIPTION
**Pull request by AndreeaMariaP**
Added login page content

### CODE REVIEW

**Comment by tudoramariei** [comment]
The `clock.svg` image should be changed to the one below
We changed some things in the design and didn't get to update them in the main Figma doc

clock

**Comment by tudoramariei** [comment]
Also, we've changed the description to the one below. That means without the `bullet_*` fields.

```
Pentru a obține acces în NGO Hub, un reprezentant al organizației trebuie să completeze formularul următor, oferind date despre organizație și membri.  Acest prim pas de înregistrare presupune doar introducerea datelor legale, inclusiv încărcarea statutul organizației.
```
And, in English:
```
To access NGO Hub, an organization representative must fill out the following form, providing information about the organization and its members. This initial registration step involves only entering legal data, including uploading the organization's statute.
```

**Comment by AndreeaMariaP** [comment]
I've updated the image and translations @tudoramariei 👍

**Review by tudoramariei — APPROVED** [review]
It looks good from a content side 😁

**Review by radulescuandrew — APPROVED** [review]

**Pull request merged**
